server:
  address: ":8090"
  api_prefix: "/api"

log:
  level: "debug"
  enable_trace: true
  json_format: false

tracer:
  endpoint: http://localhost:14269/api/traces
  environment: dev

database:
  driver: "sqlite"
  source: "../database.source"